name: Scheduler

# https://help.github.com/en/github/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule
on:
  schedule:
    - cron:  '*/6 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: reminder
      run: python reminder.py
      env:
        URL: ${{ secrets.URL }}
